use crate::types::{Chat, Contact, Message};

pub fn get_mock_logs() -> Vec<String> {
    vec![
        "[00:15:10] [SYSTEM] NodeChat initialization started...".to_string(),
        "[00:15:11] [STORAGE] SQLite WAL mode enabled successfully.".to_string(),
        "[00:15:11] [STORAGE] Loaded local identity: key_ed25519_23f81b...".to_string(),
        "[00:15:12] [P2P] iroh-gossip service listening on port 6831.".to_string(),
        "[00:15:13] [P2P] Discovered local DHT bootstrap peer.".to_string(),
        "[00:15:14] [CRYPTO] Local security key derived from user PIN.".to_string(),
    ]
}

pub fn get_mock_chats() -> Vec<Chat> {
    vec![
        Chat {
            id: "alice".to_string(),
            name: "Alice Vance".to_string(),
            initials: "AV".to_string(),
            last_message: "Did you verify my safety number?".to_string(),
            timestamp: "12:44 PM".to_string(),
            unread: 2,
            is_group: false,
            is_online: true,
            is_verified: true,
            has_queued: false,
            messages: vec![
                Message {
                    id: "a1".to_string(),
                    sender: "Alice Vance".to_string(),
                    text: "Hey, are you online?".to_string(),
                    timestamp: "12:30 PM".to_string(),
                    is_outgoing: false,
                    is_system: false,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
                Message {
                    id: "a2".to_string(),
                    sender: "You".to_string(),
                    text: "Yes, I'm here! NodeChat transport feels very fast on Dioxus."
                        .to_string(),
                    timestamp: "12:32 PM".to_string(),
                    is_outgoing: true,
                    is_system: false,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
                Message {
                    id: "sys1".to_string(),
                    sender: "".to_string(),
                    text: "🔒 Session keys ratcheted. Forward secrecy active.".to_string(),
                    timestamp: "12:32 PM".to_string(),
                    is_outgoing: false,
                    is_system: true,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
                Message {
                    id: "a3".to_string(),
                    sender: "Alice Vance".to_string(),
                    text: "Did you verify my safety number?".to_string(),
                    timestamp: "12:44 PM".to_string(),
                    is_outgoing: false,
                    is_system: false,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
            ],
        },
        Chat {
            id: "bob".to_string(),
            name: "Bob Builder".to_string(),
            initials: "BB".to_string(),
            last_message: "Sure, here is the bootstrap ticket: iroh://...".to_string(),
            timestamp: "Yesterday".to_string(),
            unread: 0,
            is_group: false,
            is_online: false,
            is_verified: false,
            has_queued: false,
            messages: vec![
                Message {
                    id: "b1".to_string(),
                    sender: "Bob Builder".to_string(),
                    text: "Hey, can you send me the peer ticket?".to_string(),
                    timestamp: "Yesterday".to_string(),
                    is_outgoing: false,
                    is_system: false,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
                Message {
                    id: "b2".to_string(),
                    sender: "You".to_string(),
                    text: "Sure, here is the bootstrap ticket: iroh://...".to_string(),
                    timestamp: "Yesterday".to_string(),
                    is_outgoing: true,
                    is_system: false,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
            ],
        },
        Chat {
            id: "system_bot".to_string(),
            name: "System Bot".to_string(),
            initials: "SB".to_string(),
            last_message: "Group Invite: Decentralized Devs".to_string(),
            timestamp: "3 days ago".to_string(),
            unread: 0,
            is_group: false,
            is_online: true,
            is_verified: true,
            has_queued: false,
            messages: vec![
                Message {
                    id: "sb1".to_string(),
                    sender: "System Bot".to_string(),
                    text: "Welcome to NodeChat! Here is an invite to join the main channel."
                        .to_string(),
                    timestamp: "3 days ago".to_string(),
                    is_outgoing: false,
                    is_system: false,
                    is_invite: false,
                    invite_group_name: "".to_string(),
                    invite_desc: "".to_string(),
                    invite_topic_id: "".to_string(),
                    invite_key: "".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
                Message {
                    id: "sb2".to_string(),
                    sender: "System Bot".to_string(),
                    text: "invite_stub".to_string(),
                    timestamp: "3 days ago".to_string(),
                    is_outgoing: false,
                    is_system: false,
                    is_invite: true,
                    invite_group_name: "Decentralized Devs".to_string(),
                    invite_desc:
                        "A group for discussing decentralized protocols and iroh gossip mechanisms."
                            .to_string(),
                    invite_topic_id: "topic_decentralized_devs".to_string(),
                    invite_key: "key_secp256k1_decentralized".to_string(),
                    invite_joined: false,
                    status: "read".to_string(),
                    is_contact_share: false,
                    share_name: String::new(),
                    share_node_id: String::new(),
                    share_ticket: String::new(),
                },
            ],
        },
    ]
}

pub fn get_mock_contacts() -> Vec<Contact> {
    vec![
        Contact {
            id: "alice".to_string(),
            name: "Alice Vance".to_string(),
            initials: "AV".to_string(),
            node_id: "iroh://peer/alice_node_id_hash_2348a".to_string(),
            is_online: true,
            is_verified: true,
        },
        Contact {
            id: "bob".to_string(),
            name: "Bob Builder".to_string(),
            initials: "BB".to_string(),
            node_id: "iroh://peer/bob_node_id_hash_5839b".to_string(),
            is_online: false,
            is_verified: false,
        },
        Contact {
            id: "charlie".to_string(),
            name: "Charlie Chat".to_string(),
            initials: "CC".to_string(),
            node_id: "iroh://peer/charlie_node_id_hash_9182c".to_string(),
            is_online: true,
            is_verified: false,
        },
        Contact {
            id: "dave".to_string(),
            name: "Dave Dev".to_string(),
            initials: "DD".to_string(),
            node_id: "iroh://peer/dave_node_id_hash_7761d".to_string(),
            is_online: true,
            is_verified: true,
        },
    ]
}
