export component ActionRow inherits Rectangle {
    in property <string> label: "";
    in property <color> background-color;
    in property <color> text-color;
    in property <length> font-size: 16px;

    callback clicked();

    height: 56px;
    border-radius: 18px;
    background: background-color;

    TouchArea {
        clicked => { root.clicked(); }
        Text {
            text: label;
            font-size: font-size;
            font-weight: 800;
            color: text-color;
            horizontal-alignment: center;
            vertical-alignment: center;
        }
    }
}
